service: serverless-node-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    SECRET_NAME: ${env:SECRET_NAME}
    SECdRET_ARN: ${env:SECRET_ARN}

functions:
  helloWorld:
    handler: api/app.handler
    events:
      - http:
          path: /
          method: get

  getUser:
    handler: api/users.handler
    memorySize: 128
    description: Get single user from db
    events:
      - http:
          path: /users/{userId}
          method: get
  listUsers:
    handler: api/users.handler
    memorySize: 128
    description: Get all users from the db
    events:
      - http:
          path: /users
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin