service: serverless-node-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    STAGE: ${env:STAGE}
    USERS_TABLE: 'users-${opt:stage, self:provider.stage}'


functions:
  helloWorld:
    handler: api/app.handler
    events:
      - http:
          path: /
          method: get

  createUser:
    handler: api/users.handler
    memorySize: 128
    description: Create a new user
    events:
      - http:
          path: /users/create
          method: post
  getUser:
    handler: api/users.handler
    memorySize: 128
    description: Get single user from db
    events:
      - http:
          path: /users/{userId}
          method: get
  listUsers:
    handler: api/users.handler
    memorySize: 128
    description: Get all users from the db
    events:
      - http:
          path: /users
          method: get

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USERS_TABLE}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline